### ISSUE TITLE
pyScoMotif runs error

### ISSUE THREAD

**Issue by lyp-zyl** [3BioCompBio/pyScoMotif#2]
Hi,
I encountered while using your software, pyScoMotif, for the discovery of similar 3D structural motifs across proteins. I executed the following command:
pyscomotif create-index --pattern=*.pdb.gz --n_cores=6 /home/penglan/workspace/GH_analysis/UP000005640_9606_HUMAN_v4

However, I encountered the following error:
exception calling callback for <Future at 0x7f33bd95b9d0 state=finished raised EOFError>
concurrent.futures.process._RemoteTraceback:
[...]
FileNotFoundError: [Errno 2] No such file or directory: '/home/penglan/workspace/GH_analysis/UP000005640_9606_HUMAN_v4/pyScoMotif_index/residue_data_folder/AF-A2VEC9-F1-model_v4.bz2'

It seems that there is an issue related to file handling and I am not able to proceed further with the analysis. Could you please provide some guidance or assistance in resolving this issue? Your expertise in this area would be greatly appreciated. Thank you for your time and support. I look forward to your response.
Best wishes!
Thanks!

**Comment by 3BioCompBio** [comment]
The latest version of pyScoMotif now uses the joblib library for parallel computing, which I think should solve your issue.
