### ISSUE TITLE
Indexing larger sets

### ISSUE THREAD

**Issue by amardeepranu** [3BioCompBio/pyScoMotif#3]
Great tool!

For larger pdb databases the indexing is very slow. Any tips on speeding this up - core # isn't helping that much? Would I be able to chunk pdbs (lets say 1000 at a time)  and just merge the final index outputs together (just move the files into a single index folder)? Thanks

**Comment by gciaberi** [comment]
> Great tool!
> 
> For larger pdb databases the indexing is very slow. Any tips on speeding this up - core # isn't helping that much? Would I be able to chunk pdbs (lets say 1000 at a time) and just merge the final index outputs together (just move the files into a single index folder)? Thanks

In section S4 of the supplementary of our publication we show that it took us ~ 20h30 to index 200K PDB files on a computer using 12 parallel cores. Are you obtaining something similar ?

Regarding the index merging approach you suggest, this is not currently implemented, and I don't plan to do it as the use cases are quite limited. For example, if you have multiple indexed datasets, you can just run your search on each individual indexed dataset and then merge the results files.

In your case, adding more cores is the best way to go as the indexing speed should scale linearly with the number of cores.

**Comment by amardeepranu** [comment]
Sounds good - I think it may be an I/O issue on my end if you're getting 20h on 200k. Thanks for the tip of splitting up the index, I'll try that if this persists. Thanks!
